version: '3.8'

services:
    rates:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rates
        env_file: .env
        environment:
            DB_TYPE: postgres
            DB_HOST: rates-postgres
            DB_PORT: 5432 # Ichki port, PostgreSQL uchun default port
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        ports:
            - '127.0.0.1:3000:${PORT}' # Tashqi port:3000, ichki port:3999
        volumes:
            - ./assets:/app/assets # Mount local `assets` to container `/app/assets`
            - ./uploads:/app/uploads # Optional: if you use `/uploads` for file storage
        networks:
            - app_network
        restart: unless-stopped

networks:
    app_network:
        driver: bridge # Custom network for communication between services

